### ISSUE TITLE
哥们，你实现过这个CCA-KNN吗？

### ISSUE THREAD

**Issue by EasonTong** [WERush/awesome-image-annotation#2]
我在做这个实验，使用Corel5k， 但是效果差强人意
我看你的这个项目里的pdf，但是他写道一半就没了...
想向您讨教下这个实验怎么实现，尤其是最后检索的时候....
万分感谢

**Comment by WERush** [comment]
你好，我没有实现过CCA-KNN，这个repo更多的是一个笔记性质的，里面的算法并没有复现。
